server:
  port: 8084
  servlet:
    context-path: '/ead-notification/'

spring:
  application:
    name: ead-notification-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
  datasource:
    url: jdbc:postgresql://localhost:5435/notification
    username: joel
    password: docker
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob.non-contextual-creation: true
    show-sql: true
  flyway:
    locations: classpath:db/migration, classpath:db/testdb
    baselineOnMigrate: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

